More tinkering; estimatethreshold displays more info.

diff --git a/debug-match b/debug-match
--- a/debug-match
+++ b/debug-match
@@ -1,29 +1,21 @@
 #!/bin/bash
 
 # Arguments:
-#   $1 = <image-name-A>.png
-#   $2 = <image-name-B>.png
+#   $1 = <image-name-A>
+#   $2 = <image-name-B>
 
 # 0. Check for errors #
 #   A. Check for the correct number of parameters #
 if [ "$#" -ne 2 ]; then
-  echo "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
-  exit
-#   B. Check that the first parameter ends with ".png" #
-elif [[ $1 != *.png ]]; then
-  echo "ERROR:\tFirst parameter needs to end with \".png\"."
-  exit
-#   C. Check that the second parameter ends with ".png" #
-elif [[ $2 != *.png ]]; then
-  echo "ERROR:\tSecond parameter needs to end with \".png\"."
-  exit
+  echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
+  exit 2
 fi
 
 
 # 1. Create the temporary working directory and enter it #
 MYCURRDIR=$PWD
 MYTMPDIR=`mktemp -d ` || exit 1
-trap 'rm -rf $MYTMPDIR; cd $MYCURRDIR' EXIT
+trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT
 #echo $MYTMPDIR ## debugging
 
 # 2. Convert the PNG images into WSQ images #
@@ -35,8 +27,8 @@ trap 'rm -rf $MYTMPDIR; cd $MYCURRDIR' EXIT
 ./NBIS/mindtct $MYTMPDIR/imageB.wsq $MYTMPDIR/minutiaeB > /dev/null
 
 # 4. Match the two minutiaes in xyt format #
-./NBIS/bozorth3 $MYTMPDIR/minutiaeA.xyt $MYTMPDIR/minutiaeB.xyt
-
+SCORE=`./NBIS/bozorth3 $MYTMPDIR/minutiaeA.xyt $MYTMPDIR/minutiaeB.xyt`
+echo $SCORE
 
 # Finally, delete the temporary directory #
 
@@ -44,4 +36,4 @@ cd $MYCURRDIR
 rm -rf $MYTMPDIR
 
 
-exit 0
+exit $SCORE
diff --git a/enroll b/enroll
--- a/enroll
+++ b/enroll
@@ -1,21 +1,17 @@
 #!/bin/bash
 
 # Arguments:
-#   $1 = <imagename>.png
+#   $1 = <imagename>
 #   $2 = <username>
 
 # 0. Check for errors #
 #   A. Check for the correct number of parameters #
 if [ "$#" -ne 2 ]; then
-  echo "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
-  exit 1
-#   B. Check that the first parameter ends with ".png" #
-elif [[ $1 != *.png ]]; then
-  echo "ERROR:\tFirst parameter needs to end with \".png\"."
+  echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
   exit 2
-#   C. Check to see if the username already exists #
+#   B. Check to see if the username already exists #
 elif [ -f ./database/$2.xyt ]; then
-  echo "ERROR:\tUsername already exists, choose a more unique name."
+  echo -e "ERROR:\tUsername already exists, choose a more unique name."
   exit 3
 fi
 
@@ -23,7 +19,7 @@ fi
 # 1. Create the temporary working directory and enter it #
 MYCURRDIR=$PWD
 MYTMPDIR=`mktemp -d ` || exit 1
-trap 'rm -rf $MYTMPDIR; cd $MYCURRDIR' EXIT
+trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT
 #echo $MYTMPDIR ## for debugging purposes
 
 # 2. Convert the candidate PNG image into a WSQ image #
diff --git a/match b/match
--- a/match
+++ b/match
@@ -1,21 +1,17 @@
 #!/bin/bash
 
 # Arguments:
-#   $1 = <imagename>.png
+#   $1 = <imagename>
 #   $2 = <username>
 
 # 0. Check for errors #
 #   A. Check for the correct number of parameters #
 if [ "$#" -ne 2 ]; then
-  echo "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
-  exit 1
-#   B. Check that the first parameter ends with ".png" #
-elif [[ $1 != *.png ]]; then
-  echo "ERROR:\tFirst parameter needs to end with \".png\"."
+  echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
   exit 2
-#   C. Check to see if the username exists #
+#   B. Check to see if the username exists #
 elif [ ! -f ./database/$2.xyt ]; then
-  echo "ERROR:\tUsername doesn't exists, make sure the user is enrolled."
+  echo -e "ERROR:\tUsername doesn't exists, make sure the user is enrolled."
   exit 3
 fi
 
@@ -23,7 +19,7 @@ fi
 # 1. Create the temporary working directory and enter it #
 MYCURRDIR=$PWD
 MYTMPDIR=`mktemp -d ` || exit 1
-trap 'rm -rf $MYTMPDIR; cd $MYCURRDIR' EXIT
+trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT
 #echo $MYTMPDIR ## debugging
 
 # 2. Convert the probing PNG image into a WSQ image #
@@ -33,8 +29,8 @@ trap 'rm -rf $MYTMPDIR; cd $MYCURRDIR' EXIT
 ./NBIS/mindtct $MYTMPDIR/image.wsq $MYTMPDIR/minutiae > /dev/null
 
 # 4. Match the probing minutiae to a username's minutiae in xyt format #
-./NBIS/bozorth3 $MYTMPDIR/minutiae.xyt ./database/$2.xyt
-
+SCORE=`./NBIS/bozorth3 $MYTMPDIR/minutiae.xyt ./database/$2.xyt`
+echo $SCORE
 
 # Finally, delete the temporary directory #
 
@@ -42,5 +38,5 @@ cd $MYCURRDIR
 rm -rf $MYTMPDIR
 
 
-exit 0
+exit $SCORE
 
