Added qualitystatistics, update test-match and estimatethreshold

diff --git a/enroll b/enroll
--- a/enroll
+++ b/enroll
@@ -4,15 +4,24 @@
 #   $1 = <imagename>
 #   $2 = <username>
 
+# To Return:
+FAIL_NUM_PARAMS=1
+FAIL_USERNAME=2
+RETURN=0
+# SUCCESS -> RETURN == 0
+# Should never be below 0 (undefined behavior)
+
 # 0. Check for errors #
 #   A. Check for the correct number of parameters #
 if [ "$#" -ne 2 ]; then
   echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
-  exit 2
+  RETURN=$FAIL_NUM_PARAMS
+  exit $RETURN
 #   B. Check to see if the username already exists #
 elif [ -f ./database/$2.xyt ]; then
   echo -e "ERROR:\tUsername already exists, choose a more unique name."
-  exit 3
+  RETURN=$FAIL_USERNAME
+  exit $RETURN
 fi
 
 
@@ -24,6 +33,14 @@ trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT
 
 # 2. Convert the candidate PNG image into a WSQ image #
 ./Cognaxon/convertWSQ $1 $MYTMPDIR/image > /dev/null
+
+#2a. Check to make sure image quality is less than 3 (1 or 2) #
+if ! [ $(./NBIS/nfiq $MYTMPDIR/image.wsq) -lt 3 ]; then
+  echo -e "ERROR:\tImage quality is not good enough. Retake image."
+  cd $MYCURRDIR
+  rm -rf $MYTMPDIR
+  exit 3
+fi
 
 # 3. Extract the candidate WSQ image's minutiae #
 ./NBIS/mindtct $MYTMPDIR/image.wsq $MYTMPDIR/$2 > /dev/null
diff --git a/match b/match
--- a/match
+++ b/match
@@ -4,37 +4,58 @@
 #   $1 = <imagename>
 #   $2 = <username>
 
+
+QUALITY=5
+#QUALITY=4 # Images' quality scores must be better than QUALITY
+
+
+# To Return:
+FAIL=0
+# SUCCESS -> RETURN > 0
+# Should never be below 0 (undefined behavior)
+
+
 # 0. Check for errors #
 #   A. Check for the correct number of parameters #
 if [ "$#" -ne 2 ]; then
-  echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
-  exit 2
+  echo -e "Usage: ./test-quality PATH_TO_IMAGE USERNAME"
+  echo $FAIL
+  exit $FAIL
 #   B. Check to see if the username exists #
 elif [ ! -f ./database/$2.xyt ]; then
-  echo -e "ERROR:\tUsername doesn't exists, make sure the user is enrolled."
-  exit 3
+  echo -e "ERROR:\tUsername doesn't exist in database, make sure the user is enrolled."
+  echo $FAIL
+  exit $FAIL
 fi
 
 
 # 1. Create the temporary working directory and enter it #
 MYCURRDIR=$PWD
-MYTMPDIR=`mktemp -d ` || exit 1
+MYTMPDIR=`mktemp -d ` || (echo $FAIL && exit $FAIL)
 trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT
+
 
 # 2. Convert the probing PNG image into a WSQ image #
 ./Cognaxon/convertWSQ $1 $MYTMPDIR/image > /dev/null
 
-# 3. Extract the probing WSQ image's minutiae #
+
+# 3. Check to make sure image quality is between 1 and ($QUALITY-1) #
+QUALITYA=$(./NBIS/nfiq $MYTMPDIR/image.wsq)
+if ! [ $QUALITYA -lt $QUALITY ]; then
+  echo -e "ERROR:\tImage quality ($QUALITYA) is not good enough. Retake image."
+  echo $FAIL
+  exit
+fi
+
+
+# 4. Extract the probing WSQ image's minutiae #
 ./NBIS/mindtct $MYTMPDIR/image.wsq $MYTMPDIR/minutiae > /dev/null
 
-# 4. Match the probing minutiae to a username's minutiae in xyt format #
+
+# 5. Match the probing minutiae to a username's minutiae in xyt format #
 SCORE=`./NBIS/bozorth3 $MYTMPDIR/minutiae.xyt ./database/$2.xyt`
+
+
+# 6. Set RETURN value as the score #
 echo $SCORE
-
-# 5. Finally, delete the temporary working directory #
-cd $MYCURRDIR
-rm -rf $MYTMPDIR
-
-
-exit $SCORE
 
diff --git a/test-match b/test-match
--- a/test-match
+++ b/test-match
@@ -4,38 +4,54 @@
 #   $1 = <image-name-A>
 #   $2 = <image-name-B>
 
+#QUALITY=4 # Images' quality scores must be better than QUALITY
+QUALITY=5
+
+# To Return:
+FAIL=0
+# SUCCESS -> RETURN > 0
+# Should never be below 0 (undefined behavior)
+###echo "args: '$1' '$2'"
 # 0. Check for errors #
 #   A. Check for the correct number of parameters #
 if [ "$#" -ne 2 ]; then
   echo -e "ERROR:\tIllegal number of parameters:\tExpected 2, there were $#."
-  exit 2
+  exit $FAIL
 fi
-
 
 # 1. Create the temporary working directory and enter it #
 MYCURRDIR=$PWD
-MYTMPDIR=`mktemp -d ` || exit 1
-trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR' EXIT
-#echo "MYTMPDIR=$MYTMPDIR" ## debugging
+MYTMPDIR=`mktemp -d ` || exit $FAIL
+#trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR; exit $RETURN' EXIT
+#trap 'cd $MYCURRDIR; rm -rf $MYTMPDIR; echo $RETURN; exit $RETURN' EXIT  # debugging
 
 # 2. Convert the PNG images into WSQ images #
-#echo "Convert the PNG images into WSQ images" ## debugging
 ./Cognaxon/convertWSQ $1 $MYTMPDIR/imageA > /dev/null
 ./Cognaxon/convertWSQ $2 $MYTMPDIR/imageB > /dev/null
 
-# 3. Extract each WSQ image's minutiae #
-#echo "Extract each WSQ image's minutiae" ## debugging
+# 3. Check to make sure image quality is between 1 and ($QUALITY-1) #
+QUALITYA=$(./NBIS/nfiq $MYTMPDIR/imageA.wsq)
+QUALITYB=$(./NBIS/nfiq $MYTMPDIR/imageB.wsq)
+if ! [ $QUALITYA -lt $QUALITY          \
+    -a $QUALITYB -lt $QUALITY ]; then
+  if [ $QUALITYA -lt $QUALITY ]; then
+    echo -e "ERROR:\tImage quality of arg2 ($QUALITYB) is not good enough. Retake image."
+  elif [ $QUALITYB -lt $QUALITY ]; then
+    echo -e "ERROR:\tImage quality of arg1 ($QUALITYA) is not good enough. Retake image."
+  else
+    echo -e "ERROR:\tImage qualities of both images ($QUALITYA and $QUALITYB) are not good enough. Retake both images."
+  fi
+  exit $FAIL
+fi
+
+# 4. Extract each WSQ image's minutiae #
 ./NBIS/mindtct $MYTMPDIR/imageA.wsq $MYTMPDIR/minutiaeA > /dev/null
 ./NBIS/mindtct $MYTMPDIR/imageB.wsq $MYTMPDIR/minutiaeB > /dev/null
 
-# 4. Match the two minutiaes in xyt format #
-#echo "Match the two minutiaes in xyt format" ## debugging
+# 5. Match the two minutiaes in xyt format #
 SCORE=`./NBIS/bozorth3 $MYTMPDIR/minutiaeA.xyt $MYTMPDIR/minutiaeB.xyt`
-echo $SCORE
 
-# Finally, delete the temporary directory #
-cd $MYCURRDIR
-rm -rf $MYTMPDIR
-
+echo "$1 vs $2 = $SCORE"
 
 exit $SCORE
+
